In [19]:
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [20]:
df= pd.read_csv("C:/Users/atharva/OneDrive/Desktop/self learn data science/machine learning algorithms/logistic regression/flower petal prediction/IRIS.csv")
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
#check data of DV
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
#check for missing values
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [17]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [22]:
#replace the species value with numeric values
df['species'] = df['species'].replace({'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3})

In [23]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        3
146           6.3          2.5           5.0          1.9        3
147           6.5          3.0           5.2          2.0        3
148           6.2          3.4           5.4          2.3        3
149           5.9          3.0           5.1          1.8        3

[150 rows x 5 columns]

In [26]:
x_train,x_test,y_train,y_test = train_test_split(df[['sepal_length','sepal_width','petal_length','petal_width']],df['species'],train_size=0.8)

In [32]:
x_train

     sepal_length  sepal_width  petal_length  petal_width
76            6.8          2.8           4.8          1.4
127           6.1          3.0           4.9          1.8
6             4.6          3.4           1.4          0.3
93            5.0          2.3           3.3          1.0
16            5.4          3.9           1.3          0.4
..            ...          ...           ...          ...
84            5.4          3.0           4.5          1.5
58            6.6          2.9           4.6          1.3
71            6.1          2.8           4.0          1.3
135           7.7          3.0           6.1          2.3
75            6.6          3.0           4.4          1.4

[120 rows x 4 columns]

In [33]:
y_train

76     2
127    3
6      1
93     2
16     1
      ..
84     2
58     2
71     2
135    3
75     2
Name: species, Length: 120, dtype: int64

In [34]:
from sklearn import linear_model
model= linear_model.LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [35]:
model.predict(x_test)

array([2, 1, 3, 1, 3, 2, 2, 3, 1, 2, 2, 2, 1, 2, 2, 3, 2, 1, 3, 1, 1, 3,
       2, 2, 3, 3, 3, 1, 3, 2], dtype=int64)

In [36]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
85            6.0          3.4           4.5          1.6
42            4.4          3.2           1.3          0.2
124           6.7          3.3           5.7          2.1
24            4.8          3.4           1.9          0.2
126           6.2          2.8           4.8          1.8
81            5.5          2.4           3.7          1.0
61            5.9          3.0           4.2          1.5
141           6.9          3.1           5.1          2.3
39            5.1          3.4           1.5          0.2
82            5.8          2.7           3.9          1.2
50            7.0          3.2           4.7          1.4
60            5.0          2.0           3.5          1.0
40            5.0          3.5           1.3          0.3
98            5.1          2.5           3.0          1.1
89            5.5          2.5           4.0          1.3
146           6.3          2.5           5.0          1.9
63            6.1          2.9           4.7          1.4
19            5.1          3.8           1.5          0.3
100           6.3          3.3           6.0          2.5
13            4.3          3.0           1.1          0.1
47            4.6          3.2           1.4          0.2
70            5.9          3.2           4.8          1.8
80            5.5          2.4           3.8          1.1
99            5.7          2.8           4.1          1.3
142           5.8          2.7           5.1          1.9
118           7.7          2.6           6.9          2.3
113           5.7          2.5           5.0          2.0
44            5.1          3.8           1.9          0.4
112           6.8          3.0           5.5          2.1
62            6.0          2.2           4.0          1.0

In [41]:
predicted_output = model.score(x_test,y_test)

In [45]:
from sklearn.metrics import confusion_matrix

In [50]:
com = confusion_matrix (y_test, predicted_output)
com

InvalidParameterError: The 'y_pred' parameter of confusion_matrix must be an array-like. Got 0.9666666666666667 instead.

In [49]:
import seaborn as sn
from matplotlib import pyplot as plt
plt.figure(figsize=(5,4))
sn.heatmap(cm,annot=True)
plt.xlabel('predicted value')
plt.ylabel('truth or  actual value')

NameError: name 'cm' is not defined