In [ ]:
# 1 import libraries
# 2 create data frame and import dataset
# 3 define IV and DV inside X and Y objects
# 4 split data into train and test data
# develop svm model
# predict results of the model
# check score of the model

In [3]:
import pandas as pd

In [9]:
df= pd.read_csv("C:/Users/atharva/OneDrive/Desktop/self learn data science/machine learning algorithms/SVM Classification/IRIS.csv")
df

      Id  sepal_length  sepal_width  petal_length  petal_width         species
0      1           5.1          3.5           1.4          0.2     Iris-setosa
1      2           4.9          3.0           1.4          0.2     Iris-setosa
2      3           4.7          3.2           1.3          0.2     Iris-setosa
3      4           4.6          3.1           1.5          0.2     Iris-setosa
4      5           5.0          3.6           1.4          0.2     Iris-setosa
..   ...           ...          ...           ...          ...             ...
145  146           6.7          3.0           5.2          2.3  Iris-virginica
146  147           6.3          2.5           5.0          1.9  Iris-virginica
147  148           6.5          3.0           5.2          2.0  Iris-virginica
148  149           6.2          3.4           5.4          2.3  Iris-virginica
149  150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 6 columns]

In [10]:
#define X and Y (IV and DV)
x = df.iloc[:,0:5]
x

      Id  sepal_length  sepal_width  petal_length  petal_width
0      1           5.1          3.5           1.4          0.2
1      2           4.9          3.0           1.4          0.2
2      3           4.7          3.2           1.3          0.2
3      4           4.6          3.1           1.5          0.2
4      5           5.0          3.6           1.4          0.2
..   ...           ...          ...           ...          ...
145  146           6.7          3.0           5.2          2.3
146  147           6.3          2.5           5.0          1.9
147  148           6.5          3.0           5.2          2.0
148  149           6.2          3.4           5.4          2.3
149  150           5.9          3.0           5.1          1.8

[150 rows x 5 columns]

In [11]:
y=df.iloc[:,5]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [12]:
#split dataset into training and testing data

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [13]:
# develop svm model

from sklearn.svm import SVC

In [14]:
#define kernel for 2d dataset
model = SVC(kernel = 'linear')

In [18]:
len(x_test)

30

In [19]:
x_test

      Id  sepal_length  sepal_width  petal_length  petal_width
50    51           7.0          3.2           4.7          1.4
124  125           6.7          3.3           5.7          2.1
138  139           6.0          3.0           4.8          1.8
1      2           4.9          3.0           1.4          0.2
3      4           4.6          3.1           1.5          0.2
82    83           5.8          2.7           3.9          1.2
22    23           4.6          3.6           1.0          0.2
140  141           6.7          3.1           5.6          2.4
110  111           6.5          3.2           5.1          2.0
53    54           5.5          2.3           4.0          1.3
132  133           6.4          2.8           5.6          2.2
5      6           5.4          3.9           1.7          0.4
13    14           4.3          3.0           1.1          0.1
67    68           5.8          2.7           4.1          1.0
34    35           4.9          3.1           1.5          0.1
131  132           7.9          3.8           6.4          2.0
63    64           6.1          2.9           4.7          1.4
36    37           5.5          3.5           1.3          0.2
103  104           6.3          2.9           5.6          1.8
145  146           6.7          3.0           5.2          2.3
54    55           6.5          2.8           4.6          1.5
6      7           4.6          3.4           1.4          0.3
104  105           6.5          3.0           5.8          2.2
21    22           5.1          3.7           1.5          0.4
18    19           5.7          3.8           1.7          0.3
30    31           4.8          3.1           1.6          0.2
32    33           5.2          4.1           1.5          0.1
76    77           6.8          2.8           4.8          1.4
125  126           7.2          3.2           6.0          1.8
112  113           6.8          3.0           5.5          2.1

In [20]:
model.predict(x_test)

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [21]:
# check model score

model.score(x_test, y_test)

1.0